# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.ffbmessaging
canonical: http://fhir.kl.dk/ffbmessaging
name: KLFFBMessaging
title: Please provide a good title
description: Please provide a good description
status: active # draft # active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release # ci-build # release
publisher:
  name: KL
  url: http://www.kl.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  hl7.fhir.dk.core: 1.1.0
  kl.dk.fhir.term: 1.0.0
  kl.dk.fhir.core: 1.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
